[build]
  publish = "public"
  command = "npm run build"

[functions]
  directory = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
