[build]
  command = "npm install"  # Ensure dependencies are installed
  publish = "/"            # Use root directory for static sites

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
