[build]
  command = "npm install && npm run build"  # Ensures dependencies are installed before the build
  publish = "public"  # Change to "dist" or the correct directory if using a different build system

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
