[build]
  command = "npm install && npm run build"
  publish = "/"  # Serve from root since there's no dedicated build output directory

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
